spring.application.name=gym-fee-management
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/gym_db}
spring.datasource.username=${DB_USERNAME:gymuser}
spring.datasource.password=${DB_PASSWORD:gympass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.serialization.write-dates-as-timestamps=false
